image: tossp/lede:latest

stages:
  - 测试阶段
  - 构建阶段
  - 部署阶段

编译打包:
  stage: 构建阶段
  cache:
    key: build-key-cache
    paths:
    - key-build
    - key-build.pub
  environment:
    name: 'production'
    url: http://lede-k3.test.tossp.com/$CI_COMMIT_SHA/index.html
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    FORCE_UNSAFE_CONFIGURE: '1'
    TS_QN_BUCKET: 'lede-k3'
  artifacts:
      name: "${CI_JOB_STAGE}_${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
      expire_in: 6 mos
      paths:
        - bin/
  script:
    - mkdir -p /ts/$CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG/{dl,feeds,build_dir,staging_dir}
    # - make clean
    # - ./scripts/feeds clean -a
    - ln -s /ts/$CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG/dl dl
    - ln -s /ts/$CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG/feeds feeds
    - ln -s /ts/$CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG/staging_dir staging_dir
    - sed -i "s/CI_COMMIT_SHA/$CI_COMMIT_SHA/g" ./package/ts/ts-settings/files/ts-default-settings
    - sed -i "s/COMMIT_SHA_VERSION/${CI_COMMIT_SHA:0:8}/g" ./package/ts/ts-settings/Makefile
    - ./scripts/feeds update -a
    - ./scripts/feeds install -a
    - cp tsconfig .config
    - make defconfig
    - (make -j$(nproc) V=s 2>&1 | tee build.txt | grep -E -e "time.+(#[\.0-9]+){3}" -e 'make\[[1-3]\].{2}(Leav|Enter)ing directory.+') || (grep -P 'Error \d+\b(?! \(ignored\))' -C5 build.txt && exit 66)
    - cp bin/targets/bcm53xx/generic/config.seed bin/targets/bcm53xx/generic/config.seed.txt
    - cp bin/targets/bcm53xx/generic/sha256sums bin/targets/bcm53xx/generic/sha256sums.txt
    - cp .config bin/config.txt
    - cp build.txt bin/build.txt
  only:
    - ci

七牛发布:
  stage: 部署阶段
  retry: 2
  dependencies:
    - 编译打包
  environment:
    name: 'production'
    url: http://lede-k3.test.tossp.com/$CI_COMMIT_SHA/index.html
  variables:
    TS_QN_BUCKET: 'lede-k3'
  script:    
    - wget -O /bin/qshell http://devtools.qiniu.com/2.1.5/qshell-linux-x64
    - chmod a+x /bin/qshell
    - qshell account $QNAK $QNSK
    - cp index.tmpl bin/index.html
    - tree -L 5 bin/ > bin/tree.txt
    - TSTIME=`date '+%Y-%m-%d %H:%M:%S' -d '8 hours'`
    - sed -i "s/CI_COMMIT_SHA/$CI_COMMIT_SHA/g" bin/index.html
    - sed -i "s/CI_RUNNER_DESCRIPTION/$CI_RUNNER_DESCRIPTION/g" bin/index.html
    - sed -i "s/CI_RUNNER_TAGS/$CI_RUNNER_TAGS/g" bin/index.html
    - sed -i "s/CI_BUILD_TIME/$TSTIME/g" bin/index.html
    - mkdir -p $CI_COMMIT_SHA
    - mv -f bin/* $CI_COMMIT_SHA
    - mv -f $CI_COMMIT_SHA bin/
    - cp bin/$CI_COMMIT_SHA/index.html bin/
    - qshell listbucket lede-k3 his 
    - grep '/index.html' his | sort -k4 -r | awk 'BEGIN{FS="[/\t]"} {print "{\"id\":\""$1"\",\"time\":\""$5"\"}\n,"}' | sed -e '1i [' -e '$c ]' > bin/history.json
    - qshell qupload2 -log-file /root/ts.log -check-exists -check-hash -check-size -overwrite -rescan-local -thread-count 6 -src-dir bin -bucket $TS_QN_BUCKET
    - cat /root/ts.log
  only:
    - ci
