image: tossp/lede:latest

stages:
  - 测试阶段
  - 构建阶段
  - 部署阶段
     
构建编译:
  stage: 构建阶段
  retry: 1
  variables:
    FORCE_UNSAFE_CONFIGURE: '1'  
  artifacts:
    name: "${CI_JOB_STAGE}_${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    expire_in: 6 mos
    paths:
      - bin/
  script:
    - mkdir -p /ts/$CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG/{dl,feeds,build_dir,staging_dir}
   # - make clean
   # - ./scripts/feeds clean -a
    - ln -s /ts/$CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG/dl dl
    - ln -s /ts/$CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG/feeds feeds
    - ln -s /ts/$CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG/staging_dir staging_dir
    - ./scripts/feeds update -a 
    - ./scripts/feeds install -a
    - cp tsconfig .config
    - make defconfig
    - make -j$(nproc) V=1
   # - make -j1 V=1
    - cp .config bin/config.txt
  only:
    - ci
     
七牛发布:
  stage: 部署阶段
  retry: 2
  dependencies:
    - 构建编译
  environment:
    name: 'QN-OSS'
    url: http://lede-k3.test.tossp.com/$CI_COMMIT_SHA/index.html
  variables:
    TS_QN_BUCKET: 'lede-k3'
  script:
    - cp index.tmpl bin/index.html
    - tree -L 5 bin/ > bin/tree.txt
    - TSTIME=`date '+%Y-%m-%d %H:%M:%S' -d '8 hours'`
    - sed -i "s/CI_COMMIT_SHA/$CI_COMMIT_SHA/g" bin/index.html
    - sed -i "s/CI_RUNNER_DESCRIPTION/$CI_RUNNER_DESCRIPTION/g" bin/index.html
    - sed -i "s/CI_RUNNER_TAGS/$CI_RUNNER_TAGS/g" bin/index.html
    - sed -i "s/CI_BUILD_TIME/$TSTIME/g" bin/index.html
    - mkdir -p $CI_COMMIT_SHA
    - mv -f bin/* $CI_COMMIT_SHA
    - mv -f $CI_COMMIT_SHA bin/
    - cp bin/$CI_COMMIT_SHA/index.html bin/
    - wget -O /bin/qshell http://devtools.qiniu.com/2.1.5/qshell-linux-x64
    - chmod a+x /bin/qshell
    - qshell account $QNAK $QNSK
    - qshell qupload2 -log-file /root/ts.log -check-exists -check-hash -check-size -overwrite -rescan-local -thread-count 6 -src-dir bin -bucket $TS_QN_BUCKET
    - cat /root/ts.log
  only:
    - ci